// Generated by generate_state_machine_cpp.py from state_machine.puml
// DO NOT EDIT MANUALLY.

#pragma once

#include <cstdint>

namespace app {

enum class State {
    Error_Display,
    Error_Touch,
    Flipping,
    Halted,
    InitDisplay,
    InitTouch,
    Initializing,
    Ready,
    ResultShown,
};

enum class Event {
    evButtonClick,
    evDisplayFail,
    evDisplayOk,
    evFlipComplete,
    evReboot,
    evReset,
    evSerialOk,
    evTouchFail,
    evTouchOk,
};

struct Context {
    // Populated by the hand-written service layer.
};

class StateMachine {
public:
    StateMachine() : state_(State::Initializing) {}

    State current() const { return state_; }

    void dispatch(Event event, Context& ctx);

    // Guards
    virtual bool guard_TFT_eSPI_missing_or_not_display_ok(const Context& ctx) const = 0;
    virtual bool guard_TFT_eSPI_present(const Context& ctx) const = 0;
    virtual bool guard_XPT2046_missing_or_not_touch_ok(const Context& ctx) const = 0;
    virtual bool guard_XPT2046_present(const Context& ctx) const = 0;
    virtual bool guard_btnFlip_enabled(const Context& ctx) const = 0;
    virtual bool guard_esp_random_ok(const Context& ctx) const = 0;
    virtual bool guard_reboot_available(const Context& ctx) const = 0;
    virtual bool guard_runtime_display_fail(const Context& ctx) const = 0;
    virtual bool guard_runtime_touch_fail(const Context& ctx) const = 0;
    virtual bool guard_serial_required(const Context& ctx) const = 0;
    virtual bool guard_ui_ready(const Context& ctx) const = 0;

    // Actions
    virtual void coin_flip_ui_set_result_log_coin_result() = 0;
    virtual void init_serial() = 0;
    virtual void init_tft() = 0;
    virtual void on_display_init_failed() = 0;
    virtual void on_flip_button_clicked() = 0;
    virtual void on_touch_init_failed() = 0;
    virtual void reboot() = 0;
    virtual void ui_create() = 0;
    virtual void ui_set_result_Tap_Flip() = 0;

private:
    State state_;
};

} // namespace app
